### ISSUE TITLE
Is is possible to merge slide/scale/rotate into one extension?

### ISSUE THREAD

**Issue by m13253** [mengzhuo/gnome-shell-window-open-animation-slide-in#3]
Is is possible to merge slide/scale/rotate into one extension?
It is really annoying that I have to uninstall and reinstall if I just want to change another animation.

Would you please develop a framework of window animation that it is easy to manage window animations just like Compiz did? Thanks.

**Comment by mengzhuo** [comment]
Yes. I'm still working on it. I got to said, it's too hard for me to design a framework like Compiz, especially on read out the status arguments of original window from the WindowManager. 
I've already made the a JSON data fetcher and other infrastructure.
Hands needed, are you in?

**Comment by mengzhuo** [comment]
The extension that I mention:
https://github.com/mengzhuo/gnome-shell-animation-center

**Comment by m13253** [comment]
I am willing to join your project, but wait, perhaps I need to learn some GNOME developing stuff first, I am not familiar with it. :-)

I appreciate for your work! Good job!

**Comment by m13253** [comment]
哎呀，原来你是北京的呀。。。。说了半天English。。。 :-)

**Comment by mengzhuo** [comment]
囧～看了下你的repos，原来是个大大！Gnome Shell Extension是用Gnome Javascript+Glib+Gio等开发的，外观用CSS控制，其实蛮简单的。现在的技术难点是：我想学JQuery Animate那一套，但是没什么头绪。
